### ISSUE TITLE
Feature Request: Support for "SHORTCUTURL" as producted by Firefox

### ISSUE THREAD

**Issue by ReedClanton** [FlyingWolFox/Netscape-Bookmarks-File-Parser#8]
# Description

Firefox supports associating shortcut keywords with bookmarks. When the keyword is entered in the top bar that's associated with a bookmark, Firefox will automatically navigate to that bookmarked page. This field is currently ignored.

# Example Firefox Export

```
<DT><A HREF="http://bookmarkurl/" ADD_DATE="1705518475" LAST_MODIFIED="1705518610" SHORTCUTURL="bookmarkmenukeyword" TAGS="BookmarkMenuTag">BookmarkMenuName</A>
```

**Comment by FlyingWolFox** [comment]
Hello again @ReedClanton!

Support for the `SHORTCUTURL` attribute was added. Thank you for the sugestion!
If you encounter any problem with this attribute, just reopen the issue.

Regards,
FlyingWolFox
